version: 2

updates:
  - package-ecosystem: composer
    directory: "/api/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (php) "
    target-branch: main
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: "/api/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (js) "
    target-branch: main
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: "/app/src-tauri"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (js) "
    target-branch: main
    open-pull-requests-limit: 1

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (github actions) "
    target-branch: main
    open-pull-requests-limit: 1

  - package-ecosystem: docker
    directory: "/api/environment/dev/app"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (docker dev) "
    target-branch: main
    open-pull-requests-limit: 1

  - package-ecosystem: cargo
    directory: "/app/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (js) "
    target-branch: main
    open-pull-requests-limit: 1
